### ISSUE TITLE
Can you add a "collection" command?

### ISSUE THREAD

**Issue by Cerzs** [xxami/boo#3]
Hi, @xxami!

Can you add a bot command for listing your cards? It would be amazing.

**Comment by xxami** [comment]
unfortunately i haven't touched boo in some years, if it was a trivial change i would try to add it for you, but to list all the cards (which, there might be 100+ depending on the set), it would need some multi-page system - which on discord is usually done with emoji reactions (:arrow_left: :arrow_right:) and editing or deleting/reposting the next pages.

that sounds like too much work for now, maybe i will remake boo in the future to handle that, but for now i'd recommend looking at some more fleshed out bots that other people have created (maybe https://top.gg/bot/432610292342587392 if it's for pokemon) :P

**Comment by Cerzs** [comment]
I see! I was looking to adding my own cards for my server tbh, like Love Live, Azur Lane, etc. Hope you do that remake, I find boo interesting and simple. Thank you!
